# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"*\n\x0eRequestMessage\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\n\n\x02Id\x18\x02 \x01(\x05\"/\n\x0fRequestResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0e\n\x06result\x18\x02 \x01(\x08\"\x07\n\x05\x45mpty\",\n\rCurrentLeader\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"\x19\n\x06Period\x12\x0f\n\x07seconds\x18\x01 \x01(\x05\x32\xab\x01\n\x0bRaftService\x12\x30\n\x0bRequestVote\x12\x0f.RequestMessage\x1a\x10.RequestResponse\x12)\n\x0e\x41ppendEnteries\x12\x0f.RequestMessage\x1a\x06.Empty\x12#\n\tGetLeader\x12\x06.Empty\x1a\x0e.CurrentLeader\x12\x1a\n\x07Suspend\x12\x07.Period\x1a\x06.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTMESSAGE._serialized_start=14
  _REQUESTMESSAGE._serialized_end=56
  _REQUESTRESPONSE._serialized_start=58
  _REQUESTRESPONSE._serialized_end=105
  _EMPTY._serialized_start=107
  _EMPTY._serialized_end=114
  _CURRENTLEADER._serialized_start=116
  _CURRENTLEADER._serialized_end=160
  _PERIOD._serialized_start=162
  _PERIOD._serialized_end=187
  _RAFTSERVICE._serialized_start=190
  _RAFTSERVICE._serialized_end=361
# @@protoc_insertion_point(module_scope)
